i3-config: /home/USER/.config/i3/config
polybar: /home/USER/.config/polybar
xresources: /home/USER/.Xresources
nitrogen-config: /home/USER/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/USER/.config/nitrogen/
