i3-config: /home/marc/.config/i3/config
polybar: /home/marc/.config/polybar/
xresources: /home/marc/.Xresources
nitrogen-config: /home/marc/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/marc/.config/nitrogen/
